#!/bin/bash

# Execute all scripts to collect statistics about COVID-19 cases

SPATH=$(dirname $0)
DATADIR=$(dirname $SPATH)/data
echo $DATADIR
pushd $SPATH

# Get information from various sources

for SCRIPT in get_*
do
    . $SCRIPT $DATADIR
done

popd

# Keep only on copy of identical files

pushd $DATADIR

git pull

md5sum *.csv \
| sort \
| awk -F ' ' 'BEGIN { F="" } { if (F==$1) { print ("rm", $2 ) ;}  else { print ( "#Keep ", $2 ) ; F=$1; }}' \
| sh

git add *
git commit -m "New data"
git push
popd
